config/routes.rb
Rails.application.routes.draw do
  resources :user_areas
  resources :cards
  resources :groups
  resources :usuarios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # Routes to change card status
  put '/change_next_status/:id', to: 'cards#changeNextStatus', as: 'next_status'
  put '/change_previous_status/:id', to: 'cards#changePreviousStatus', as: 'previous_status'

  #Routes to filter cards by status
  get '/cards/status/:status', to: 'cards#index', as: 'cards_filter'

  #Routes to filter cards by group
  get '/cards/group/:group_id', to: 'cards#index', as: 'cards_group_filter' 


  put '/add_user_to_card/:id', to: 'cards#add_user_to_card', as: 'add_user_to_card'

  # Defines the root path route ("/")
  # root "articles#index"

  put '/add_user_to_card/:id', to: 'cards#add_user_to_card', as: 'user_to_card'

  root 'welcome#index'

  #User routes
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  #Sessions routes
  get '/login', to: 'sessions#login'
  post 'sign_in', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

end

app/views/shared/_footer.html.erb
<footer>
    <div class="left text">
        All rights reserved. - Privacy Policy - Terms of Services
    </div>

    <div class="right text">
        Supported by MyPOD Company - 2022 MyPOD.
    </div>
</footer>

app/views/shared/_header.html.erb
<header>
    <div>
        <a class="logo-link" href=<%= root_path %>>
            <%= image_tag("app_logo.png", width:'200') %>
        </a>
    </div>

    <div class="header-menu">
        <%= link_to "MyHome", root_path, class: "nav-button" %>
        <%= link_to "MyTasks", cards_path, class: "nav-button" %>
        <%= link_to "MyUser", usuarios_path, class: "nav-button" %>
    </div>

    <div></div>
</header>