config/routes.rb
Rails.application.routes.draw do
  resources :user_areas
  resources :cards
  resources :groups
  resources :usuarios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # Routes to change card status
  put '/change_next_status/:id', to: 'cards#changeNextStatus', as: 'next_status'
  put '/change_previous_status/:id', to: 'cards#changePreviousStatus', as: 'previous_status'

  #Routes to filter cards by status
  get '/cards/status/:status', to: 'cards#index', as: 'cards_filter'

  #Routes to filter cards by group
  get '/cards/group/:group_id', to: 'cards#index', as: 'cards_group_filter' 


  put '/add_user_to_card/:id', to: 'cards#add_user_to_card', as: 'add_user_to_card'

  # Defines the root path route ("/")
  # root "articles#index"

  put '/add_user_to_card/:id', to: 'cards#add_user_to_card', as: 'user_to_card'

  root 'welcome#index'

  #User routes
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  #Sessions routes
  get '/login', to: 'sessions#login'
  post 'sign_in', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

end

app/models/card.rb
class Card < ApplicationRecord
    validates :name, presence: true
    belongs_to :group

    def nextStatus
        case self.status
            when 'todo'   
                self.status = :doing 
            when 'doing'
                self.status = :done 
            else
                self.status = :todo 
        end
    end

    def previousStatus
        case self.status
            when 'todo'   
                self.status = :done 
            when 'doing'
                self.status = :todo 
            else
                self.status = :doing 
        end
    end

    def add_user_to_card
        case self.cadastro_usuario_id 
            when nil
                self.cadastro_usuario_id = 1
            when 1
                self.cadastro_usuario_id = nil
        end
    end
    
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ show edit update destroy changeNextStatus changePreviousStatus ]

  # GET /cards or /cards.json
  def index
      if params[:status]
      @cards = filter(params[:status])
      elsif params[:group_id]
        @cards = group_filter(params[:group_id])
      else
        @cards = Card.all
      end
      # these are the groups buttons that appear on the left
      @groups = Group.all
    
  end

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    
    @card = Card.new(card_params)
    respond_to do |format|
      if @card.save
        format.html { redirect_to card_url(@card), notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to card_url(@card), notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def changeNextStatus()
    @card.nextStatus
    @card.save
    redirect_to '/cards'
  end

  def changePreviousStatus()
    @card.previousStatus
    @card.save
    redirect_to '/cards'     
  end

  def add_user_to_card()
    @card = Card.find_by(id: params[:id])
    @card.update(cadastro_usuario_id: session[:user_id])
    @card.save
    redirect_to '/cards'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:name, :description, :status, :group_id)
    end

    

    def filter(status)
      case status
        when 'todo'   
          return Card.where(status: 'todo')
        when 'doing'
          return Card.where(status: 'doing') 
        else
          return Card.where(status: 'done')
        end
    end

    def group_filter(group_id)
      return Card.where(group_id: group_id)
    end
  end

app/helpers/cards_helper.rb
module CardsHelper

    def format_status(status)
        case status
            when 'todo'   
                status = 'To Do' 
            when 'doing'
                status = 'Doing' 
            else
                status = 'Done' 
        end
        status
    end


end

app/views/cards/_card.html.erb
<div id="<%= dom_id card %>" class="card">
  <div class="card-title">
  <%= button_to 'Claim card', add_user_to_card_path(card.id), method: :put, class: "card-status-btn" %>
        <span><%= link_to "#{card.name} - ", "/cards/#{card.id}/edit" %></span>
        <span class="card-group">
            <%= link_to Group.find(card.group_id).description, edit_group_path(card.group) %>
        </span>
  </div>
  
  <div class="card-description">
      <span><%= card.description %></span>
  </div>
  <div class="card-bottom">
      <div class="card-bottom-timer">
          <button class="card-status-btn">
          <a href="/cards/<%= card.id %>/edit">
              <img class="card-bottom-timer-img" src="/assets/edit_card.png" alt="">
          </a>
          </button>
      </div>
      
      <span>Owner: <%=
      if (@usuario = CadastroUsuario.find_by(id: @card_id = card.cadastro_usuario_id))
        @usuario.nome
      end
      %></span>
      <div class="card-status">
      Owner:
      <%=        
      if card.cadastro_usuario_id 
          @usuario = CadastroUsuario.find_by(id: card.cadastro_usuario_id)
          @usuario.nome
      end
      %>
          <%= button_to '<', previous_status_path(card.id), method: :put, class: "card-status-btn" %>
          <span><%= format_status(card.status) %></span>
          
          <%= button_to '>', next_status_path(card.id), method: :put, class: "card-status-btn" %>
      </div>
  </div>
</div>

app/views/cards/_form.html.erb
<%= form_with(model: card, id:"form") do |form| %>
  <% if card.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.select(:status, options_for_select([['To Do', 'todo'], ['Doing', 'doing'], ['Done', 'done']], 1)) %>
  </div>

  <div>
    <%= form.label :group_id, style: "display: block" %>
    <%= form.collection_select(:group_id, Group.all, :id, :description, prompt: true) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
  
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Show this card", @card %> |
  <%= link_to "Back to cards", cards_path %>
</div>

app/views/cards/index.html.erb
<p style="color: green"><%= notice %></p>

<div class='dashboard'>
  <h1>Cards</h1>
  <div class='dashboard-news'>
    <a class="dashboard-filter-btn" href="/groups/new" id="new-group">
      + New Group
    </a>
    <a class="dashboard-filter-btn" href="/cards/new">
      + New Card
    </a>
  </div>
  <div class="dashboard-content">
    <div class="dashboard-filter">
      <div class="dashboard-filter-reset">
          <%= button_to 'Reset Filters', cards_path('todo'), method: :get, class: "dashboard-filter-btn" %>
      </div>
      <div class="dashboard-filter-general">
          <%= button_to 'To Do-Filter', cards_filter_path('todo'), method: :get, class: "dashboard-filter-btn" %>
          <%= button_to 'Doing-Filter', cards_filter_path('doing'), method: :get, class: "dashboard-filter-btn" %>
          <%= button_to 'Done-Filter', cards_filter_path('done'), method: :get, class: "dashboard-filter-btn" %>    
      </div>

      <div class="dashboard-filter-group">
        <% @groups.each do |group| %>
          <%= button_to "#{group.description}", cards_group_filter_path(group.id), method: :get, class: "dashboard-filter-btn" %> 
        <% end %>
      </div> 
    </div>

  
   
    
    <div class="dashboard-cards">
      <% @cards.each do |card| %>
      <div id="card_<%=card.id%>">
        <%= render card %>
      </div>  
      <% end %>
    </div>
  </div>
</div>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Back to cards", cards_path %>
</div>

app/views/cards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @card %>

<div>
  <%= link_to "Edit this card", edit_card_path(@card) %> |
  <%= link_to "Back to cards", cards_path %>

  <%= button_to "Destroy this card", @card, method: :delete %>
</div>